{% set version = "0.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bindr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bindr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bindr/bindr_{{ version }}.tar.gz
  sha256: 521f6c60183c8c0c9a4e27a3e923349d17cbd9638dc6ba29bf803c8e840f2698

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('bindr')"           # [not win]
    - "\"%R%\" -e \"library('bindr')\""  # [win]

about:
  home: https://github.com/krlmlr/bindr, https://krlmlr.github.io/bindr
  license: MIT
  summary: Provides a simple interface for creating active bindings where the bound function accepts additional arguments.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
